#!/usr/bin/env ruby
require_relative 'dynamize_factories'

files = ARGV[0] || './sample.rb'

files = File.join(files, '*.rb') if File.directory?files

Dir[files].each do |file|
  begin
    df = DynamizeFactories.new file
    df.put_it_back
  rescue StandardError => e
    puts "Error in file: #{file}"
    puts e
  end
end
